// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wllurrpyhxagnjzyrtrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbHVycnB5aHhhZ25qenlydHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTQ1MDMsImV4cCI6MjA2NDE3MDUwM30.FV_QojiFSfPTeZtGMxVy_-nrFxxDhEduVz_iZU1NL4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);